# This workflow installs Python dependencies and runs tests with several versions of Python on MacOS, Ubuntu and Windows.
# Releases and PyPI publishing are handled by release.yml (release-please).
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

env:
  POETRY_VERSION: "1.2.2"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run tests (${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install libkrb5-dev
        run: sudo apt-get -y install libkrb5-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Install poetry ${{ env.POETRY_VERSION }}
        run: |
          pip install poetry==${{ env.POETRY_VERSION }}

      - name: Install aws-adfs and its dependencies
        run: |
          poetry install

      - name: Run all pre-commit checks
        if: matrix.os == 'ubuntu-latest'
        run: |
          poetry run pre-commit run --all

      - name: Test with pytest
        run: |
          poetry run pytest
